// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/providers/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:flutter/material.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:ollamaverse/models/app_settings.dart' as _i2;
import 'package:ollamaverse/models/chat.dart' as _i11;
import 'package:ollamaverse/models/ollama_model.dart' as _i5;
import 'package:ollamaverse/providers/settings_provider.dart' as _i7;
import 'package:ollamaverse/services/ollama_service.dart' as _i3;
import 'package:ollamaverse/services/storage_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOllamaService_1 extends _i1.SmartFake implements _i3.OllamaService {
  _FakeOllamaService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OllamaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOllamaService extends _i1.Mock implements _i3.OllamaService {
  MockOllamaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeAppSettings_0(this, Invocation.getter(#settings)),
          )
          as _i2.AppSettings);

  @override
  set settings(_i2.AppSettings? _settings) => super.noSuchMethod(
    Invocation.setter(#settings, _settings),
    returnValueForMissingStub: null,
  );

  @override
  void updateSettings(_i2.AppSettings? newSettings, {String? newAuthToken}) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [newSettings],
          {#newAuthToken: newAuthToken},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancelGeneration() => super.noSuchMethod(
    Invocation.method(#cancelGeneration, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.OllamaModel>> getModels() =>
      (super.noSuchMethod(
            Invocation.method(#getModels, []),
            returnValue: _i4.Future<List<_i5.OllamaModel>>.value(
              <_i5.OllamaModel>[],
            ),
          )
          as _i4.Future<List<_i5.OllamaModel>>);

  @override
  _i4.Future<String> generateResponse({
    required String? modelName,
    required String? prompt,
    List<String>? attachedFiles,
    List<dynamic>? context,
    bool? stream = false,
    dynamic Function(String)? onStreamResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateResponse, [], {
              #modelName: modelName,
              #prompt: prompt,
              #attachedFiles: attachedFiles,
              #context: context,
              #stream: stream,
              #onStreamResponse: onStreamResponse,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateResponse, [], {
                  #modelName: modelName,
                  #prompt: prompt,
                  #attachedFiles: attachedFiles,
                  #context: context,
                  #stream: stream,
                  #onStreamResponse: onStreamResponse,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i7.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeAppSettings_0(this, Invocation.getter(#settings)),
          )
          as _i2.AppSettings);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  _i8.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i8.ThemeMode.system,
          )
          as _i8.ThemeMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> updateSettings({
    String? ollamaHost,
    int? ollamaPort,
    String? authToken,
    double? fontSize,
    bool? darkMode,
    bool? showLiveResponse,
    int? contextLength,
    String? systemPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [], {
              #ollamaHost: ollamaHost,
              #ollamaPort: ollamaPort,
              #authToken: authToken,
              #fontSize: fontSize,
              #darkMode: darkMode,
              #showLiveResponse: showLiveResponse,
              #contextLength: contextLength,
              #systemPrompt: systemPrompt,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i3.OllamaService getOllamaService() =>
      (super.noSuchMethod(
            Invocation.method(#getOllamaService, []),
            returnValue: _FakeOllamaService_1(
              this,
              Invocation.method(#getOllamaService, []),
            ),
          )
          as _i3.OllamaService);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i10.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveSettings(_i2.AppSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AppSettings> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i4.Future<_i2.AppSettings>.value(
              _FakeAppSettings_0(this, Invocation.method(#loadSettings, [])),
            ),
          )
          as _i4.Future<_i2.AppSettings>);

  @override
  _i4.Future<void> saveChat(_i11.Chat? chat) =>
      (super.noSuchMethod(
            Invocation.method(#saveChat, [chat]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i11.Chat?> loadChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#loadChat, [chatId]),
            returnValue: _i4.Future<_i11.Chat?>.value(),
          )
          as _i4.Future<_i11.Chat?>);

  @override
  _i4.Future<List<_i11.Chat>> loadAllChats() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllChats, []),
            returnValue: _i4.Future<List<_i11.Chat>>.value(<_i11.Chat>[]),
          )
          as _i4.Future<List<_i11.Chat>>);

  @override
  _i4.Future<void> deleteChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [chatId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
