// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/widgets/chat_generation_settings_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ollamaverse/models/app_settings.dart' as _i2;
import 'package:ollamaverse/models/chat.dart' as _i10;
import 'package:ollamaverse/models/generation_settings.dart' as _i5;
import 'package:ollamaverse/models/message.dart' as _i12;
import 'package:ollamaverse/providers/chat_provider.dart' as _i9;
import 'package:ollamaverse/providers/settings_provider.dart' as _i4;
import 'package:ollamaverse/services/file_content_processor.dart' as _i11;
import 'package:ollamaverse/services/ollama_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOllamaService_1 extends _i1.SmartFake implements _i3.OllamaService {
  _FakeOllamaService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsProvider_2 extends _i1.SmartFake
    implements _i4.SettingsProvider {
  _FakeSettingsProvider_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationSettings_3 extends _i1.SmartFake
    implements _i5.GenerationSettings {
  _FakeGenerationSettings_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i4.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeAppSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.AppSettings);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> updateSettings({
    String? ollamaHost,
    int? ollamaPort,
    String? authToken,
    double? fontSize,
    bool? showLiveResponse,
    int? contextLength,
    String? systemPrompt,
    bool? thinkingBubbleDefaultExpanded,
    bool? thinkingBubbleAutoCollapse,
    bool? darkMode,
    _i5.GenerationSettings? generationSettings,
    bool? validateSettings = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [],
          {
            #ollamaHost: ollamaHost,
            #ollamaPort: ollamaPort,
            #authToken: authToken,
            #fontSize: fontSize,
            #showLiveResponse: showLiveResponse,
            #contextLength: contextLength,
            #systemPrompt: systemPrompt,
            #thinkingBubbleDefaultExpanded: thinkingBubbleDefaultExpanded,
            #thinkingBubbleAutoCollapse: thinkingBubbleAutoCollapse,
            #darkMode: darkMode,
            #generationSettings: generationSettings,
            #validateSettings: validateSettings,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.OllamaService getOllamaService() => (super.noSuchMethod(
        Invocation.method(
          #getOllamaService,
          [],
        ),
        returnValue: _FakeOllamaService_1(
          this,
          Invocation.method(
            #getOllamaService,
            [],
          ),
        ),
      ) as _i3.OllamaService);

  @override
  _i6.Future<String> getLastSelectedModel() => (super.noSuchMethod(
        Invocation.method(
          #getLastSelectedModel,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLastSelectedModel,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> setLastSelectedModel(String? modelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastSelectedModel,
          [modelName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void refreshSettings() => super.noSuchMethod(
        Invocation.method(
          #refreshSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> validateCurrentSettings() => (super.noSuchMethod(
        Invocation.method(
          #validateCurrentSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int getSettingsHealthScore() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsHealthScore,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  String getSettingsStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsStatus,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getSettingsStatus,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.Future<void> autoFixSettings() => (super.noSuchMethod(
        Invocation.method(
          #autoFixSettings,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool shouldUpdateExistingChats(_i2.AppSettings? oldSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldUpdateExistingChats,
          [oldSettings],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> validateGenerationSettings(
          _i5.GenerationSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateGenerationSettings,
          [settings],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getHelpfulErrorMessage(
    String? field,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHelpfulErrorMessage,
          [
            field,
            value,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getHelpfulErrorMessage,
            [
              field,
              value,
            ],
          ),
        ),
      ) as String);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatProvider extends _i1.Mock implements _i9.ChatProvider {
  MockChatProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.Chat> get chats => (super.noSuchMethod(
        Invocation.getter(#chats),
        returnValue: <_i10.Chat>[],
      ) as List<_i10.Chat>);

  @override
  List<String> get availableModels => (super.noSuchMethod(
        Invocation.getter(#availableModels),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isGenerating => (super.noSuchMethod(
        Invocation.getter(#isGenerating),
        returnValue: false,
      ) as bool);

  @override
  bool get isSendingMessage => (super.noSuchMethod(
        Invocation.getter(#isSendingMessage),
        returnValue: false,
      ) as bool);

  @override
  bool get isProcessingFiles => (super.noSuchMethod(
        Invocation.getter(#isProcessingFiles),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnyOperationInProgress => (super.noSuchMethod(
        Invocation.getter(#isAnyOperationInProgress),
        returnValue: false,
      ) as bool);

  @override
  bool get isActiveChatGenerating => (super.noSuchMethod(
        Invocation.getter(#isActiveChatGenerating),
        returnValue: false,
      ) as bool);

  @override
  bool get isActiveChatBusy => (super.noSuchMethod(
        Invocation.getter(#isActiveChatBusy),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i11.FileProcessingProgress> get fileProcessingProgress =>
      (super.noSuchMethod(
        Invocation.getter(#fileProcessingProgress),
        returnValue: <String, _i11.FileProcessingProgress>{},
      ) as Map<String, _i11.FileProcessingProgress>);

  @override
  String get currentStreamingResponse => (super.noSuchMethod(
        Invocation.getter(#currentStreamingResponse),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#currentStreamingResponse),
        ),
      ) as String);

  @override
  String get currentDisplayResponse => (super.noSuchMethod(
        Invocation.getter(#currentDisplayResponse),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#currentDisplayResponse),
        ),
      ) as String);

  @override
  String get currentThinkingContent => (super.noSuchMethod(
        Invocation.getter(#currentThinkingContent),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#currentThinkingContent),
        ),
      ) as String);

  @override
  bool get hasActiveThinkingBubble => (super.noSuchMethod(
        Invocation.getter(#hasActiveThinkingBubble),
        returnValue: false,
      ) as bool);

  @override
  bool get isThinkingPhase => (super.noSuchMethod(
        Invocation.getter(#isThinkingPhase),
        returnValue: false,
      ) as bool);

  @override
  bool get isInsideThinkingBlock => (super.noSuchMethod(
        Invocation.getter(#isInsideThinkingBlock),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldScrollToBottomOnChatSwitch => (super.noSuchMethod(
        Invocation.getter(#shouldScrollToBottomOnChatSwitch),
        returnValue: false,
      ) as bool);

  @override
  _i4.SettingsProvider get settingsProvider => (super.noSuchMethod(
        Invocation.getter(#settingsProvider),
        returnValue: _FakeSettingsProvider_2(
          this,
          Invocation.getter(#settingsProvider),
        ),
      ) as _i4.SettingsProvider);

  @override
  bool get isGeneratingTitle => (super.noSuchMethod(
        Invocation.getter(#isGeneratingTitle),
        returnValue: false,
      ) as bool);

  @override
  List<_i12.Message> get displayableMessages => (super.noSuchMethod(
        Invocation.getter(#displayableMessages),
        returnValue: <_i12.Message>[],
      ) as List<_i12.Message>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isChatGeneratingTitle(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #isChatGeneratingTitle,
          [chatId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isThinkingBubbleExpanded(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #isThinkingBubbleExpanded,
          [messageId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void toggleThinkingBubble(String? messageId) => super.noSuchMethod(
        Invocation.method(
          #toggleThinkingBubble,
          [messageId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool chatHasCustomSettings(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #chatHasCustomSettings,
          [chatId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.GenerationSettings getEffectiveSettingsForChat(String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEffectiveSettingsForChat,
          [chatId],
        ),
        returnValue: _FakeGenerationSettings_3(
          this,
          Invocation.method(
            #getEffectiveSettingsForChat,
            [chatId],
          ),
        ),
      ) as _i5.GenerationSettings);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancelGeneration() => super.noSuchMethod(
        Invocation.method(
          #cancelGeneration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> createNewChat([String? modelName]) => (super.noSuchMethod(
        Invocation.method(
          #createNewChat,
          [modelName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateChatSystemPrompt(String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatSystemPrompt,
          [chatId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateAllChatsSystemPrompt() => (super.noSuchMethod(
        Invocation.method(
          #updateAllChatsSystemPrompt,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setActiveChat(String? chatId) => super.noSuchMethod(
        Invocation.method(
          #setActiveChat,
          [chatId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetScrollToBottomFlag() => super.noSuchMethod(
        Invocation.method(
          #resetScrollToBottomFlag,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> updateChatTitle(
    String? chatId,
    String? newTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatTitle,
          [
            chatId,
            newTitle,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateChatModel(
    String? chatId,
    String? newModelName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatModel,
          [
            chatId,
            newModelName,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateChatGenerationSettings(
    String? chatId,
    _i5.GenerationSettings? customSettings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatGenerationSettings,
          [
            chatId,
            customSettings,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendMessage(
    String? content, {
    List<String>? attachedFiles,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [content],
          {#attachedFiles: attachedFiles},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendMessageWithOptionalChatCreation(
    String? message, {
    List<String>? attachedFiles,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageWithOptionalChatCreation,
          [message],
          {#attachedFiles: attachedFiles},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshModels() => (super.noSuchMethod(
        Invocation.method(
          #refreshModels,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> retryConnection() => (super.noSuchMethod(
        Invocation.method(
          #retryConnection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> validateCurrentModelSystemPromptSupport() =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCurrentModelSystemPromptSupport,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  String getCurrentModelSystemPromptStrategy() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentModelSystemPromptStrategy,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentModelSystemPromptStrategy,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> getErrorRecoveryStatus() => (super.noSuchMethod(
        Invocation.method(
          #getErrorRecoveryStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i6.Future<Map<String, dynamic>> validateSettingsForCurrentModel() =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSettingsForCurrentModel,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> recoverService(String? serviceName) => (super.noSuchMethod(
        Invocation.method(
          #recoverService,
          [serviceName],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void clearAllServiceErrors() => super.noSuchMethod(
        Invocation.method(
          #clearAllServiceErrors,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleGlobalSettingsChange() => super.noSuchMethod(
        Invocation.method(
          #handleGlobalSettingsChange,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> getServiceHealthStatus() => (super.noSuchMethod(
        Invocation.method(
          #getServiceHealthStatus,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  bool validateAllServiceStates() => (super.noSuchMethod(
        Invocation.method(
          #validateAllServiceStates,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> resetAllServiceStates() => (super.noSuchMethod(
        Invocation.method(
          #resetAllServiceStates,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
