// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/widgets/generation_settings_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ollamaverse/models/app_settings.dart' as _i2;
import 'package:ollamaverse/models/generation_settings.dart' as _i6;
import 'package:ollamaverse/providers/settings_provider.dart' as _i4;
import 'package:ollamaverse/services/ollama_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOllamaService_1 extends _i1.SmartFake implements _i3.OllamaService {
  _FakeOllamaService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i4.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeAppSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.AppSettings);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateSettings({
    String? ollamaHost,
    int? ollamaPort,
    String? authToken,
    double? fontSize,
    bool? showLiveResponse,
    int? contextLength,
    String? systemPrompt,
    bool? thinkingBubbleDefaultExpanded,
    bool? thinkingBubbleAutoCollapse,
    bool? darkMode,
    _i6.GenerationSettings? generationSettings,
    bool? validateSettings = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [],
          {
            #ollamaHost: ollamaHost,
            #ollamaPort: ollamaPort,
            #authToken: authToken,
            #fontSize: fontSize,
            #showLiveResponse: showLiveResponse,
            #contextLength: contextLength,
            #systemPrompt: systemPrompt,
            #thinkingBubbleDefaultExpanded: thinkingBubbleDefaultExpanded,
            #thinkingBubbleAutoCollapse: thinkingBubbleAutoCollapse,
            #darkMode: darkMode,
            #generationSettings: generationSettings,
            #validateSettings: validateSettings,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.OllamaService getOllamaService() => (super.noSuchMethod(
        Invocation.method(
          #getOllamaService,
          [],
        ),
        returnValue: _FakeOllamaService_1(
          this,
          Invocation.method(
            #getOllamaService,
            [],
          ),
        ),
      ) as _i3.OllamaService);

  @override
  _i5.Future<String> getLastSelectedModel() => (super.noSuchMethod(
        Invocation.method(
          #getLastSelectedModel,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLastSelectedModel,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setLastSelectedModel(String? modelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastSelectedModel,
          [modelName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void refreshSettings() => super.noSuchMethod(
        Invocation.method(
          #refreshSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> validateCurrentSettings() => (super.noSuchMethod(
        Invocation.method(
          #validateCurrentSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int getSettingsHealthScore() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsHealthScore,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  String getSettingsStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSettingsStatus,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getSettingsStatus,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> autoFixSettings() => (super.noSuchMethod(
        Invocation.method(
          #autoFixSettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool shouldUpdateExistingChats(_i2.AppSettings? oldSettings) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldUpdateExistingChats,
          [oldSettings],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> validateGenerationSettings(
          _i6.GenerationSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateGenerationSettings,
          [settings],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getHelpfulErrorMessage(
    String? field,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHelpfulErrorMessage,
          [
            field,
            value,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getHelpfulErrorMessage,
            [
              field,
              value,
            ],
          ),
        ),
      ) as String);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
