// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/services/chat_title_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ollamaverse/models/message.dart' as _i6;
import 'package:ollamaverse/models/ollama_response.dart' as _i2;
import 'package:ollamaverse/models/processed_file.dart' as _i5;
import 'package:ollamaverse/services/ollama_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOllamaResponse_0 extends _i1.SmartFake
    implements _i2.OllamaResponse {
  _FakeOllamaResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OllamaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOllamaService extends _i1.Mock implements _i3.OllamaService {
  MockOllamaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> getModels() => (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> refreshModels() => (super.noSuchMethod(
        Invocation.method(
          #refreshModels,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.OllamaResponse> generateResponseWithContext(
    String? prompt, {
    String? model,
    List<_i5.ProcessedFile>? processedFiles,
    List<int>? context,
    List<_i6.Message>? conversationHistory,
    int? contextLength,
    bool Function()? isCancelled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithContext,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
            #conversationHistory: conversationHistory,
            #contextLength: contextLength,
            #isCancelled: isCancelled,
          },
        ),
        returnValue: _i4.Future<_i2.OllamaResponse>.value(_FakeOllamaResponse_0(
          this,
          Invocation.method(
            #generateResponseWithContext,
            [prompt],
            {
              #model: model,
              #processedFiles: processedFiles,
              #context: context,
              #conversationHistory: conversationHistory,
              #contextLength: contextLength,
              #isCancelled: isCancelled,
            },
          ),
        )),
      ) as _i4.Future<_i2.OllamaResponse>);

  @override
  _i4.Future<String> generateResponseWithFiles(
    String? prompt, {
    String? model,
    List<_i5.ProcessedFile>? processedFiles,
    List<int>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithFiles,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithFiles,
            [prompt],
            {
              #model: model,
              #processedFiles: processedFiles,
              #context: context,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Stream<_i2.OllamaStreamResponse> generateStreamingResponseWithContext(
    String? prompt, {
    String? model,
    List<_i5.ProcessedFile>? processedFiles,
    List<int>? context,
    List<_i6.Message>? conversationHistory,
    int? contextLength,
    bool Function()? isCancelled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStreamingResponseWithContext,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
            #conversationHistory: conversationHistory,
            #contextLength: contextLength,
            #isCancelled: isCancelled,
          },
        ),
        returnValue: _i4.Stream<_i2.OllamaStreamResponse>.empty(),
      ) as _i4.Stream<_i2.OllamaStreamResponse>);

  @override
  _i4.Stream<String> generateStreamingResponseWithFiles(
    String? prompt, {
    String? model,
    List<_i5.ProcessedFile>? processedFiles,
    List<int>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStreamingResponseWithFiles,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
          },
        ),
        returnValue: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Future<Map<String, dynamic>> validateSystemPromptSupport(
          String? modelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSystemPromptSupport,
          [modelName],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  String getSystemPromptStrategy(String? modelName) => (super.noSuchMethod(
        Invocation.method(
          #getSystemPromptStrategy,
          [modelName],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getSystemPromptStrategy,
            [modelName],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
