// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/services/chat_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ollamaverse/models/chat.dart' as _i4;
import 'package:ollamaverse/services/chat_history_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChatHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatHistoryService extends _i1.Mock
    implements _i2.ChatHistoryService {
  MockChatHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Chat>> get chatStream => (super.noSuchMethod(
        Invocation.getter(#chatStream),
        returnValue: _i3.Stream<List<_i4.Chat>>.empty(),
      ) as _i3.Stream<List<_i4.Chat>>);

  @override
  List<_i4.Chat> get chats => (super.noSuchMethod(
        Invocation.getter(#chats),
        returnValue: <_i4.Chat>[],
      ) as List<_i4.Chat>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> saveChat(_i4.Chat? chat) => (super.noSuchMethod(
        Invocation.method(
          #saveChat,
          [chat],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Chat?> loadChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #loadChat,
          [chatId],
        ),
        returnValue: _i3.Future<_i4.Chat?>.value(),
      ) as _i3.Future<_i4.Chat?>);

  @override
  _i3.Future<_i4.Chat?> getChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #getChat,
          [chatId],
        ),
        returnValue: _i3.Future<_i4.Chat?>.value(),
      ) as _i3.Future<_i4.Chat?>);

  @override
  _i3.Future<void> deleteChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<String, dynamic> getCustomSettingsStats() => (super.noSuchMethod(
        Invocation.method(
          #getCustomSettingsStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
