// Mocks generated by Mockito 5.4.6 from annotations
// in ollamaverse/test/services/model_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ollamaverse/models/app_settings.dart' as _i2;
import 'package:ollamaverse/models/message.dart' as _i10;
import 'package:ollamaverse/models/ollama_response.dart' as _i4;
import 'package:ollamaverse/models/processed_file.dart' as _i9;
import 'package:ollamaverse/providers/settings_provider.dart' as _i5;
import 'package:ollamaverse/services/ollama_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOllamaService_1 extends _i1.SmartFake implements _i3.OllamaService {
  _FakeOllamaService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOllamaResponse_2 extends _i1.SmartFake
    implements _i4.OllamaResponse {
  _FakeOllamaResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i5.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeAppSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.AppSettings);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> updateSettings({
    String? ollamaHost,
    int? ollamaPort,
    String? authToken,
    double? fontSize,
    bool? showLiveResponse,
    int? contextLength,
    String? systemPrompt,
    bool? thinkingBubbleDefaultExpanded,
    bool? thinkingBubbleAutoCollapse,
    bool? darkMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [],
          {
            #ollamaHost: ollamaHost,
            #ollamaPort: ollamaPort,
            #authToken: authToken,
            #fontSize: fontSize,
            #showLiveResponse: showLiveResponse,
            #contextLength: contextLength,
            #systemPrompt: systemPrompt,
            #thinkingBubbleDefaultExpanded: thinkingBubbleDefaultExpanded,
            #thinkingBubbleAutoCollapse: thinkingBubbleAutoCollapse,
            #darkMode: darkMode,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.OllamaService getOllamaService() => (super.noSuchMethod(
        Invocation.method(
          #getOllamaService,
          [],
        ),
        returnValue: _FakeOllamaService_1(
          this,
          Invocation.method(
            #getOllamaService,
            [],
          ),
        ),
      ) as _i3.OllamaService);

  @override
  _i6.Future<String> getLastSelectedModel() => (super.noSuchMethod(
        Invocation.method(
          #getLastSelectedModel,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLastSelectedModel,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> setLastSelectedModel(String? modelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastSelectedModel,
          [modelName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OllamaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOllamaService extends _i1.Mock implements _i3.OllamaService {
  MockOllamaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<String>> getModels() => (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> refreshModels() => (super.noSuchMethod(
        Invocation.method(
          #refreshModels,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.OllamaResponse> generateResponseWithContext(
    String? prompt, {
    String? model,
    List<_i9.ProcessedFile>? processedFiles,
    List<int>? context,
    List<_i10.Message>? conversationHistory,
    int? contextLength,
    bool Function()? isCancelled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithContext,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
            #conversationHistory: conversationHistory,
            #contextLength: contextLength,
            #isCancelled: isCancelled,
          },
        ),
        returnValue: _i6.Future<_i4.OllamaResponse>.value(_FakeOllamaResponse_2(
          this,
          Invocation.method(
            #generateResponseWithContext,
            [prompt],
            {
              #model: model,
              #processedFiles: processedFiles,
              #context: context,
              #conversationHistory: conversationHistory,
              #contextLength: contextLength,
              #isCancelled: isCancelled,
            },
          ),
        )),
      ) as _i6.Future<_i4.OllamaResponse>);

  @override
  _i6.Future<String> generateResponseWithFiles(
    String? prompt, {
    String? model,
    List<_i9.ProcessedFile>? processedFiles,
    List<int>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponseWithFiles,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponseWithFiles,
            [prompt],
            {
              #model: model,
              #processedFiles: processedFiles,
              #context: context,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Stream<_i4.OllamaStreamResponse> generateStreamingResponseWithContext(
    String? prompt, {
    String? model,
    List<_i9.ProcessedFile>? processedFiles,
    List<int>? context,
    List<_i10.Message>? conversationHistory,
    int? contextLength,
    bool Function()? isCancelled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStreamingResponseWithContext,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
            #conversationHistory: conversationHistory,
            #contextLength: contextLength,
            #isCancelled: isCancelled,
          },
        ),
        returnValue: _i6.Stream<_i4.OllamaStreamResponse>.empty(),
      ) as _i6.Stream<_i4.OllamaStreamResponse>);

  @override
  _i6.Stream<String> generateStreamingResponseWithFiles(
    String? prompt, {
    String? model,
    List<_i9.ProcessedFile>? processedFiles,
    List<int>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStreamingResponseWithFiles,
          [prompt],
          {
            #model: model,
            #processedFiles: processedFiles,
            #context: context,
          },
        ),
        returnValue: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  _i6.Future<Map<String, dynamic>> validateSystemPromptSupport(
          String? modelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSystemPromptSupport,
          [modelName],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  String getSystemPromptStrategy(String? modelName) => (super.noSuchMethod(
        Invocation.method(
          #getSystemPromptStrategy,
          [modelName],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getSystemPromptStrategy,
            [modelName],
          ),
        ),
      ) as String);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
